src/java/model/Project.java
package model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author mario
 */
@Entity
@Table(name = "PROJECT")
@XmlRootElement
public class Project implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "NAME")
    private String name;
    @Size(max = 140)
    @Column(name = "DESCRIPTION")
    private String description;
    @OneToMany(mappedBy = "project", fetch = FetchType.EAGER, targetEntity = Theme.class, cascade = CascadeType.ALL)
    private List<Theme> themes;
    @OneToMany(mappedBy = "project", targetEntity = Story.class, cascade = CascadeType.ALL)
    private List<Story> stories;
    
    public Project() {
        themes = new ArrayList<>();
        stories = new ArrayList<>();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Project)) {
            return false;
        }
        Project other = (Project) object;
        return (this.id != null || other.id == null) && (this.id == null || this.id.equals(other.id));
    }

    @Override
    public String toString() {
        return "model.Project[ id=" + id + " ]";
    }

    /**
     * @return the themes
     */
    public List<Theme> getThemes() {
        return themes;
    }

    /**
     * @param themes the themes to set
     */
    public void setThemes(List<Theme> themes) {
        this.themes = themes;
    }

    /**
     * @return the stories
     */
    public List<Story> getStories() {
        return stories;
    }

    /**
     * @param stories the stories to set
     */
    public void setStories(List<Story> stories) {
        this.stories = stories;
    }

}

src/java/model/Story.java
package model;

import Util.StatusEnum;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author mario
 */
@Entity
@Table(name = "STORY")
@XmlRootElement
public class Story implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Column(name = "ID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    @NotNull
    @Size(min = 1, max = 200)
    @Column(name = "TEXT")
    private String text;    
    @ManyToOne  
    @JoinColumn(name = "THEME_ID")  
    private Theme theme;
    @NotNull
    @Column(name = "X")
    private Integer x;
    @NotNull
    @Column(name = "Y")
    private Integer y;    
    @ManyToOne  
    @JoinColumn(name = "PROJECT_ID")  
    private Project project;  
    @Enumerated(EnumType.STRING) 
    @Column(name = "STATUS")
    private StatusEnum statusEnum;
    
    
    public Story() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }


    public Integer getX() {
        return x;
    }

    public void setX(Integer x) {
        this.x = x;
    }

    public Integer getY() {
        return y;
    }

    public void setY(Integer y) {
        this.y = y;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Story)) {
            return false;
        }
        Story other = (Story) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "model.Story[ id=" + id + " ]";
    }

    /**
     * @return the theme
     */
    public Theme getTheme() {
        return theme;
    }

    /**
     * @param theme the theme to set
     */
    public void setTheme(Theme theme) {
        this.theme = theme;
    }

    /**
     * @return the project
     */
    public Project getProject() {
        return project;
    }

    /**
     * @param project the project to set
     */
    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * @return the statusEnum
     */
    public StatusEnum getStatusEnum() {
        return statusEnum;
    }

    /**
     * @param statusEnum the statusEnum to set
     */
    public void setStatusEnum(StatusEnum statusEnum) {
        this.statusEnum = statusEnum;
    }
    
    public String getStatusClass(){
        return this.getStatusEnum().getStatusClass();
    }
    
}

src/java/Bean/ProjectBean.java
package Bean;

import Service.GenericService;
import Service.ProjectService;
import Service.ThemeService;
import Util.SessionUtil;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import model.Project;
import model.Theme;

/**
 *
 * @author mariomhgf
 */
@ManagedBean
@ViewScoped
public class ProjectBean implements Serializable {

    private GenericService serviceP;
    private GenericService serviceT;
    private Project project;
    private Theme editedTheme;

    @PostConstruct
    public void init() {
        serviceP = serviceP == null ? new ProjectService() : serviceP;
        serviceT = serviceT == null ? new ThemeService() : serviceT;

        editedTheme = new Theme();

        if (getProject() == null) {
            setProject(new Project());
        }
    }

    /**
     * @return the project
     */
    public Project getProject() {
        return project;
    }

    /**
     * @param project the project to set
     */
    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * @return the editedTheme
     */
    public Theme getEditedTheme() {
        return editedTheme;
    }

    public void resetTheme() {
        this.editedTheme = new Theme();
    }

    /**
     * @param editedTheme the editedTheme to set
     */
    public void setEditedTheme(Theme editedTheme) {
        this.editedTheme = editedTheme;
        this.editedTheme = new Theme();
    }

    public void saveTheme() {
        this.editedTheme.setProject(project);
        this.editedTheme = new Theme();
    }

    public String saveProject() {
        // Inclusion
        if (project.getId() != null) {
            serviceP.update(project);
        } // Edition
        else {
            serviceP.insert(project);
        }

        this.project = new Project();

        // This guy renews the session, stablishing the list of projects
        SessionUtil.setVariableValue("#{storyBean.projects}", serviceP.getList());

        return "projects";
    }

}

src/java/Bean/ProjectsBean.java
package Bean;

import Service.GenericService;
import Service.ProjectService;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import model.Project;

/**
 *
 * @author mariomhgf
 */
@ManagedBean
@ViewScoped
public class ProjectsBean implements Serializable{
    
    private List<Project> projects;
    private Project editedProject;
    private GenericService service;
    
    @PostConstruct
    public void init(){
        service = service == null ? new ProjectService() : service;        
        setEditedProject(new Project());
        setProjects((List<Project>) service.getList());
        
    }

    public void delete(){
        service.delete(editedProject);
        // the redefinition of new editedProject is done on init()
        this.init();
        // TODO include the facesmessage informing the exclusion
    }
    
    /**
     * @return the projects
     */
    public List<Project> getProjects() {
        return projects;
    }

    /**
     * @param projects the projects to set
     */
    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

    /**
     * @return the editedProject
     */
    public Project getEditedProject() {
        return editedProject;
    }

    /**
     * @param editedProject the editedProject to set
     */
    public void setEditedProject(Project editedProject) {
        this.editedProject = editedProject;
    }
}

src/java/Bean/StoryBean.java
package Bean;

import Service.GenericService;
import Service.ProjectService;
import Service.StoryService;
import Util.StatusEnum;
import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import model.Project;
import model.Story;

/**
 *
 * @author mariomhgf
 */
@ManagedBean
@SessionScoped
public class StoryBean implements Serializable {

    // Coordinates and user story id for mooving purposes
    private Integer x;
    private Integer y;
    private Integer id;

    // Auxiliary objects
    private Story editStory;
    private Project selectedProject;

    // Service objects
    private StoryService serviceS;
    private GenericService serviceP;

    // Lists
    // The Story list is loaded just when a project is selected
    private List<Project> projects;
    private List<Story> stories;

    @PostConstruct
    public void init() {
        // Initialize services
        serviceS = serviceS == null ? new StoryService() : serviceS;
        serviceP = serviceP == null ? new ProjectService() : serviceP;

        // Initialize auxiliary objects
        editStory = new Story();
        this.setSelectedProject(selectedProject == null ? new Project() : selectedProject);

        // temporarily added
        //stories = (List<Story>) serviceS.getList();
        
        // Initialize projects array
        projects = (List<Project>) serviceP.getList();
    }

    /**
     * *
     * When a project is set in the dropdown menu, the stories of that project
     * are loaded
     */
     public boolean isWithoutProject() {
         return selectedProject == null;
     }
     
    
    /**
     * Update the position of an user story based on it's coordinates
     */
    public void updatePosition() {
        // boolean flag to inform that some user story has been found
        boolean found = false;
        
        // If some element was moved
        if (id != null) {
            // Loops al the user stories
            for (int i = 0; i < getStories().size() && !found; i++) {
                // If the user story moved was found
                if (Objects.equals(getStories().get(i).getId(), id)) {
                    // Update the element coordinates
                    getStories().get(i).setX(x);
                    getStories().get(i).setY(y);
                    // Records the updated element
                    serviceS.update(getStories().get(i));
                    found = true;
                }
            }
        }
    }

    /**
     * Saves some user story
     */
    public void saveStory() {
        // If the user Story doesn't have coordinates
        if (editStory.getX() == null || editStory.getY() == null) {
            editStory.setX(0);
            editStory.setY(0);
        }
        // Set the project wich this user story belong
        if (selectedProject != null) {
            editStory.setProject(selectedProject);
        }
        editStory.setStatusEnum(StatusEnum.todo);
        
        serviceS.insert(editStory);

        init();
    }

    private void updateStatus(StatusEnum st){
        // boolean flag to inform that some user story has been found
        boolean found = false;
        
        if (id != null) {
            // Loops al the user stories
            for (int i = 0; i < getStories().size() && !found; i++) {
                // If the user story moved was found
                if (Objects.equals(getStories().get(i).getId(), id)) {
                    getStories().get(i).setStatusEnum(st);
                    serviceS.update(getStories().get(i));
                    found = true;
                }
            }
        }
    }
    
    public void updateTodo(){
        updateStatus(StatusEnum.todo);
    }

    public void updateDoing(){
        updateStatus(StatusEnum.doing);
    }
    
    
    public void updateDone(){
        updateStatus(StatusEnum.done);
    }    
    
    public void deleteStory(){
        // boolean flag to inform that some user story has been found
        boolean found = false;
        
        if (id != null) {
            // Loops al the user stories
            for (int i = 0; i < getStories().size() && !found; i++) {
                // If the user story moved was found
                if (Objects.equals(getStories().get(i).getId(), id)) {
                    serviceS.delete(getStories().get(i));
                    setSelectedProject(this.selectedProject);
                    found = true;
                }
            }
        }
    }        
    
    /**
     * @return the stories
     */
    public List<Story> getStories() {
        return stories;
    }

    /**
     * @param stories the stories to set
     */
    public void setStories(List<Story> stories) {
        this.stories = stories;
    }

    /**
     * @return the x
     */
    public Integer getX() {
        return x;
    }

    /**
     * @param x the x to set
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * @return the y
     */
    public Integer getY() {
        return y;
    }

    /**
     * @param y the y to set
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the editStory
     */
    public Story getEditStory() {
        return editStory;
    }

    /**
     * @param editStory the editStory to set
     */
    public void setEditStory(Story editStory) {
        this.editStory = editStory;
    }

    /**
     * @return the projects
     */
    public List<Project> getProjects() {
        return projects;
    }

    /**
     * @param projects the projects to set
     */
    public void setProjects(List<Project> projects) {
        this.projects = projects;
    }

    /**
     * @return the selectedProject
     */
    public Project getSelectedProject() {
        return selectedProject;
    }

    /**
     * Return the name of the selected project. If no project is selected
     * the method returns a message to select the project
     * @return 
     */
    public String getProjectName(){
        if(selectedProject == null || selectedProject.getId() == null){
            return "Select project";
        }
        else{
            return selectedProject.getName();
        }
    }
    
    /**
     * @param selectedProject the selectedProject to set
     */
    public void setSelectedProject(Project selectedProject) {
        this.selectedProject = selectedProject;
        if (selectedProject != null) {
            stories = (List<Story>) serviceS.getByProjectId(selectedProject.getId());
        }
        else if(selectedProject == null || selectedProject.getId() == 0){
            stories.clear();
        }
    }
}

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://java.sun.com/jsf/passthrough">
    <h:head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>UStory</title>
        <link href="css/bootstrap.css" rel="stylesheet"/>
        <link href="css/ustory.css" rel="stylesheet" />
        <script>
            /**
             * Function loadModal: opens a modal
             * @returns {undefined}
             */
            function loadModal() {
                $('#myModal').modal('show');
            }
        </script>  
    </h:head>
    <h:body id="board">

        <h:form id="form">
            <!-- Hidden variables -->
            <h:inputHidden id="varX" value="#{storyBean.x}"/>
            <h:inputHidden id="varY" value="#{storyBean.y}" />
            <h:inputHidden id="varID" value="#{storyBean.id}" />
            <h:commandLink id="command" action="#{storyBean.updatePosition}">
                <f:ajax execute="@form" />
            </h:commandLink>
            <h:commandLink id="todo" action="#{storyBean.updateTodo}">                
            </h:commandLink>
            <h:commandLink id="doing" action="#{storyBean.updateDoing}">
            </h:commandLink>
            <h:commandLink id="done" action="#{storyBean.updateDone}">
            </h:commandLink>
            <h:commandLink id="delete" action="#{storyBean.deleteStory}">
            </h:commandLink>            
            
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.jsf" ><span class="glyphicon glyphicon-send"/> UStory</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                        <ul class="nav navbar-nav">
                            <!-- Links -->
                            <li><a href="projects.jsf">Projects</a></li>
                            <li><a href="users.jsf">Manage Users</a></li>
                        </ul>

                        <!-- Search bar -->
                        <!--form class="navbar-form navbar-left" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </form-->

                        <!-- Projects Dropdown -->
                        <ul class="nav navbar-nav navbar-right">
                            <li class="navbar-form">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">#{storyBean.projectName} <span class="caret"></span></a>
                                <h:selectOneListbox class="dropdown-menu" p:role="menu" id="selPrj" value="#{storyBean.selectedProject}" converter="projectConverter">
                                    <f:selectItem itemLabel="Select a project below" noSelectionOption="true"/>
                                    <f:selectItems value="#{storyBean.projects}" var="prj" itemValue="#{prj}" itemLabel="#{prj.name}" />
                                    <f:ajax event="change" execute="selPrj" render="@form"
                                            onevent="function(data) { 
                                            if (data.status === 'success') { 
                                            loadPopovers();
                                            } }"/>
                                </h:selectOneListbox>
                            </li>

                            <li class="navbar-form">
                                <!-- New User Story Button -->
                                <h:commandButton id="openModal" class="btn btn-default" 
                                                 value="New User Story"
                                                 onclick="loadModal();javascript:return false"/> 
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>            

            <!-- User stories list -->
            <div class="container-fluid" id="cont">
                <ui:repeat value="#{storyBean.stories}" var="item">                   
                    <div class="draggable" id="#{item.id}">
                        <div class="draggable" id="#{item.id}" style="top:#{item.y}px; left:#{item.x}px;">
                            <a href='#' rel='popover' data-html="true" 
                               data-cls="#{item.statusClass}" data-content="#{item.text}" 
                               title="User Story #{item.id}   
                                    &lt;div class='pull-right'&gt; 
                                    &lt;h:commandButton class='btn btn-xs' onclick='setTodo(#{item.id})' &gt;
                                            &lt;span class='glyphicon glyphicon-pencil' /&gt;

                                        &lt;/h:commandButton&gt;
                                        &lt;h:commandButton class='btn btn-xs' onclick='setDoing(#{item.id})' &gt;
                                            &lt;span class='glyphicon glyphicon-edit' /&gt;

                                        &lt;/h:commandButton&gt;
                                        &lt;h:commandButton class='btn btn-xs' onclick='setDone(#{item.id})' &gt;
                                            &lt;span class='glyphicon glyphicon-ok-sign' /&gt;
                                            &lt;f:ajax execute='@form' /&gt;    
                                        &lt;/h:commandButton&gt;
                                        &lt;h:commandButton class='btn btn-xs' onclick='deleteStory(#{item.id})' &gt;
                                            &lt;span class='glyphicon glyphicon-trash' /&gt;

                                        &lt;/h:commandButton&gt;
                                    &lt;/div&gt;">
                            </a>
                            
                        </div>
                    </div>
                </ui:repeat>
            </div>
        </h:form>            

        <!-- Modal -->
        <h:form id="modalFrm">
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- HEADER -->
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                        </div>

                        <!-- BODY -->
                        <div class="modal-body">
                            <h:outputLabel value="User Story" />
                            <h:inputTextarea rows="3" class="form-control" value="#{storyBean.editStory.text}"/>
                        </div>

                        <!-- FOOTER -->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <h:commandButton id="btnSave" class="btn btn-primary" value="Save" action="#{storyBean.saveStory}">                               
                            </h:commandButton>
                        </div>
                    </div>
                </div>
            </div>


            <script src="js/jqueryBS.js"></script>
            <script src="js/jquery-ui.js"></script>
            <script src="js/bootstrap.js"></script>
            <script>
                                                     /*
                                                      * Function called when the page is ready
                                                      * Actions:
                                                      * - Load all popover from the screen
                                                      * - Enable all of these elements as "draggable" to be moved
                                                      */
                                                     $(document).ready(loadPopovers());

                                                     function loadPopovers() {
                                                         $("a").popover('show');
                                                         $(".draggable").draggable({
                                                             containment: [0, 0, 1000, 1000],
                                                             stop: function (event, ui) {
                                                                 var position = $(this).position();
                                                                 //alert(position.top);
                                                                 $(document.getElementById("form:varX")).val(position.left);
                                                                 $(document.getElementById("form:varY")).val(position.top);
                                                                 $(document.getElementById("form:varID")).val($(this).attr("id"));
                                                                 $(document.getElementById("form:command")).click();
                                                             }
                                                         });
                                                     }
                                                     
                                                     function setTodo(val){
                                                         $(document.getElementById("form:varID")).val(val);
                                                         $(document.getElementById("form:todo")).click();
                                                     }
                                                     
                                                     function setDoing(val){
                                                         $(document.getElementById("form:varID")).val(val);
                                                         $(document.getElementById("form:doing")).click();
                                                     }
                                                     
                                                     function setDone(val){
                                                         $(document.getElementById("form:varID")).val(val);
                                                         $(document.getElementById("form:done")).click();
                                                     }
                                                     
                                                     function deleteStory(val){
                                                         $(document.getElementById("form:varID")).val(val);
                                                         $(document.getElementById("form:delete")).click();
                                                     }
            </script>
        </h:form> 
    </h:body>
</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>

        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <link rel="icon" href="../../favicon.ico"/>
        <link href="css/bootstrap.css" rel="stylesheet"/>
        <!-- Custom styles for this template -->
        <link href="css/signin.css" rel="stylesheet"/>


        <title>UStory</title>
    </h:head>

    <h:body>
        <div class="container">

            <form class="form-signin" action="j_spring_security_check" method="post">
                
                <h2 class="form-signin-heading">
                    <span class="glyphicon glyphicon-send"/>  UStory login
                </h2>
                
                <h:inputText id="j_username" required="true" p:type="text" class="form-control" 
                             p:placeholder="Email address" p:autofocus="true"/>
                <h:inputText id="j_password" required="true" p:type="password" 
                             class="form-control" p:placeholder="Password" />
                
                <br/>
                
                <h:commandButton class="btn btn-lg btn-primary btn-block" value="Login"/>
            </form>

        </div> <!-- /container -->

    </h:body>
</html>